# Generated by Django 6.0.5 on 2026-07-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0012_hospitalisation_etat_clinique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultatexamen',
            options={},
        ),
        migrations.AlterModelManagers(
            name='resultatexamen',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='resultatexamen',
            name='date_suppression',
        ),
        migrations.RemoveField(
            model_name='resultatexamen',
            name='supprime',
        ),
        migrations.RemoveField(
            model_name='resultatexamen',
            name='supprime_par',
        ),
    ]
