# Generated by Django 6.0.5 on 2026-07-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0013_alter_resultatexamen_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultatexamen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resultats/'),
        ),
    ]
