# Generated by Django 6.0.5 on 2026-07-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0014_resultatexamen_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultatexamen',
            name='date_lecture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultatexamen',
            name='lu_par_medecin',
            field=models.BooleanField(default=False),
        ),
    ]
