# Generated by Django 6.0.5 on 2026-07-10 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0015_resultatexamen_date_lecture_and_more'),
        ('personnel', '0005_pharmacien'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='personnel.medecin'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='partage_avec',
            field=models.ManyToManyField(blank=True, related_name='dossiers_partages', to='personnel.medecin'),
        ),
    ]
