# Generated by Django 6.0.5 on 2026-07-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0007_seed_takaful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('cash', 'Espèces'), ('orange_money', 'Orange Money'), ('carte', 'Carte bancaire')], max_length=20),
        ),
    ]
