# Generated by Django 6.0.5 on 2026-07-27 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_pharmacien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentadministratif',
            name='mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='infirmier',
            name='mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='laborantin',
            name='mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='pharmacien',
            name='mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='receptionniste',
            name='mot_de_passe',
        ),
    ]
